#!/usr/bin/env bash






brave-browser
gnome-terminal --geometry=86x45+0+0 --working-directory='/home/pat/Documents/farlabs/farwebs' 
gnome-terminal --geometry=86x3+962+952 --working-directory='/home/pat/Documents/farlabs/farwebs'

kill -9 $PPID
