#!/usr/bin/env bash





TWOMON_BOOL=$(xrandr --query |grep "Screen 1" | wc -l)



if [ $TWOMON_BOOL -eq 1 ]; then
        
    ##vim
    gnome-terminal --geometry=86x45+1280+343 --working-directory=/home/pat/Documents/cloudstor/phd/python_projects/scorpy-pkg --command="/usr/bin/zsh -c 'exec /usr/bin/zsh -i'" >> /dev/null 2>&1

    ##ipy
    gnome-terminal --geometry=86x29+2242+339 --working-directory=/home/pat/Documents/cloudstor/phd/python_projects/scorpy-pkg/scripts --command="/usr/bin/zsh -c '/home/pat/.miniconda3/envs/phd/bin/ipython; exec /usr/bin/zsh -i'" >> /dev/null 2>&1

    ##bash
    gnome-terminal --geometry=86x14+2242+1035 --working-directory=/home/pat/Documents/cloudstor/phd/python_projects/scorpy-pkg

else

        
    ###vim
    #gnome-terminal --geometry=86x45+0+0 --working-directory=/home/pat/Documents/cloudstor/phd/python_projects/scorpy-pkg -- /usr/bin/zsh -i -c 'conda activate phd; vim .; exec zsh'
    ###ipy
    #gnome-terminal --geometry=86x29+960+0 --working-directory=/home/pat/Documents/cloudstor/phd/python_projects/scorpy-pkg/scripts -- /usr/bin/zsh -i -c 'conda activate phd; /home/pat/.miniconda3/envs/phd/bin/ipython; exec zsh' >> /dev/null 2>&1
    ###bash
    #gnome-terminal --geometry=86x14+2242+1035 --working-directory=/home/pat/Documents/cloudstor/phd/python_projects/scorpy-pkg -- /usr/bin/zsh -i -c 'conda activate phd; exec zsh'

    ##vim
    gnome-terminal --geometry=86x45+0+0 --working-directory=/home/pat/Documents/cloudstor/phd/python_projects/scorpy-pkg
    ##ipy
    gnome-terminal --geometry=86x29+960+0 --working-directory=/home/pat/Documents/cloudstor/phd/python_projects/scorpy-pkg/scripts
    ##bash
    gnome-terminal --geometry=86x14+2242+1035 --working-directory=/home/pat/Documents/cloudstor/phd/python_projects/scorpy-pkg

fi


kill -9 $PPID





